language: cpp

sudo: required

services:
  - docker

os:
  - linux

before_install:
  - export CC=
  - export CXX=
  - export D="docker exec fedora"
  - git clone https://github.com/staticlibs/staticlib_pion.git
  - cd staticlib_pion
  - docker pull fedora
  - docker run -id --name fedora -v `pwd`/..:/src -w=/root -e "PKG_CONFIG_PATH=/src/external_asio/resources/pkgconfig_system" fedora bash

install:
  - $D dnf install -y
        pkg-config

before_script:
  - git clone https://github.com/staticlibs/external_asio.git

script:
  - set -e
  - $D cat /etc/fedora-release
  - $D bash 'echo $PKG_CONFIG_PATH'
  - $D ls -lh /src/external_asio/resources/pkgconfig_system
  - $D cat /src/external_asio/resources/pkgconfig_system/asio.pc
  - $D pkg-config --modversion asio